project_name               = "petshop"
environment                = "dev"
location                   = "westeurope"
vnet_address_space         = "10.0.0.0/16"
vnet_public_subnet_address = "10.0.1.0/24"
vnet_private_subnet_address = "10.0.2.0/24"