name: "Terraform Destroy"

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: terraform
  cancel-in-progress: true

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: true
  ARM_USE_AZUREAD: true

jobs:
  terraform-destroy:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -var-file=environments/dev.tfvars -var="my_ip=${{ secrets.ADMIN_IP }}" -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}" -auto-approve